/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gallery;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.UIManager;

/**
 *
 * @author Georgeus
 */
public class MainForm extends javax.swing.JFrame {
private static final java.lang.reflect.Type LIST_OF_OBRA_TYPE = new TypeToken<List<Obra>>() {}.getType();
public ArrayList<Obra> obras = new ArrayList(); //Las tres variables declaradas aqui son las que usare entre forms 
public JList<Obra> lstImages;
public DefaultListModel<Obra> obrasListModel;


    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        //Inicializo la lista de obras en un scrollpanel y le añado listener de el item seleccionado y del raton
        lstImages = new JList();
        jScrollPane1.setViewportView(lstImages);
        lstImages.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstImagesValueChanged(evt);
            }
        });
        lstImages.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseClicked(java.awt.event.MouseEvent evt){
                lstImagesMouseClicked(evt);
            }
        });

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnuMainForm = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCreate = new javax.swing.JMenuItem();
        mniUpdate = new javax.swing.JMenuItem();
        mniDelete = new javax.swing.JMenuItem();
        mniSave = new javax.swing.JMenuItem();
        mniSaveAndExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                MainForm.this.windowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Frank Ruehl CLM", 2, 36)); // NOI18N
        jLabel1.setText("Jorge's Gallery");

        jLabel2.setFont(new java.awt.Font("Frank Ruehl CLM", 2, 36)); // NOI18N
        jLabel2.setText("Welcome to");

        jMenu1.setText("CRUD");

        mniCreate.setText("Create");
        mniCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreateActionPerformed(evt);
            }
        });
        jMenu1.add(mniCreate);

        mniUpdate.setText("Update");
        mniUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(mniUpdate);

        mniDelete.setText("Delete");
        mniDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(mniDelete);

        mniSave.setText("Save");
        mniSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mniSave);

        mniSaveAndExit.setText("Save & Quit");
        mniSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveAndExitActionPerformed(evt);
            }
        });
        jMenu1.add(mniSaveAndExit);

        mnuMainForm.add(jMenu1);

        setJMenuBar(mnuMainForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void windowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpened
       Gson gson = new Gson();
       obrasListModel = new DefaultListModel<Obra>();
       //Leo el valor la info del json y relleno la lista con ella 
        try {
            JsonReader reader = new JsonReader(new FileReader(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\data\\obres.json"));
            obras = gson.fromJson(reader, LIST_OF_OBRA_TYPE);
            for (Obra o: obras) {
                obrasListModel.addElement(o);
            }
            //Setteo el listModel con los elementos de la lista
            lstImages.setModel(obrasListModel);
        }
        catch (FileNotFoundException fnfe) {
            fnfe.printStackTrace();
        }

       
    }//GEN-LAST:event_windowOpened

    private void mniUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateActionPerformed
        EditImageMenu preEditImage = new EditImageMenu(this, true);
        preEditImage.setVisible(true);
        
    }//GEN-LAST:event_mniUpdateActionPerformed

    private void mniCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreateActionPerformed
        InsertImageMenu insertImageMenu = new InsertImageMenu(this, true);
        insertImageMenu.setVisible(true);
    }//GEN-LAST:event_mniCreateActionPerformed

    private void mniDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteActionPerformed
        DeleteImageMenu deleteImageMenu = new DeleteImageMenu(this, true);
        deleteImageMenu.setVisible(true);
    }//GEN-LAST:event_mniDeleteActionPerformed

    private void mniSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveActionPerformed
        obrasListModel.clear();
        //Escribo la informacion en el Json
        try (Writer writer = new FileWriter(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\data\\obres.json")) {
            
            Gson gson = new GsonBuilder().create();
            gson.toJson(obras, writer);
        
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        
        for (Obra o: obras) {
                obrasListModel.addElement(o);
            }
            lstImages.setModel(obrasListModel);
    }//GEN-LAST:event_mniSaveActionPerformed
//Hace lo mismo que el metodo de arriba pero cierra la aplicacion
    private void mniSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveAndExitActionPerformed
        try (Writer writer = new FileWriter(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\data\\obres.json")) {
            
            Gson gson = new GsonBuilder().create();
            gson.toJson(obras, writer);
        
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_mniSaveAndExitActionPerformed

    private void lstImagesValueChanged(javax.swing.event.ListSelectionEvent evt){
        
    }
    
    private void lstImagesMouseClicked(java.awt.event.MouseEvent evt){
        if (evt.getClickCount() == 2) {
            EditImage editImage = new EditImage(this, true);
            editImage.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
            
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mniCreate;
    private javax.swing.JMenuItem mniDelete;
    private javax.swing.JMenuItem mniSave;
    private javax.swing.JMenuItem mniSaveAndExit;
    private javax.swing.JMenuItem mniUpdate;
    private javax.swing.JMenuBar mnuMainForm;
    // End of variables declaration//GEN-END:variables
}
